# -*- coding: utf-8 -*-

"""
messages

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FormatEnum(object):

    """Implementation of the 'Format' enum.

    TODO: type enum description here.

    Attributes:
        SMS: TODO: type description here.
        MMS: TODO: type description here.
        TTS: TODO: type description here.

    """

    SMS = 'SMS'

    MMS = 'MMS'

    TTS = 'TTS'
