# -*- coding: utf-8 -*-

"""
messages

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SourceNumberTypeEnum(object):

    """Implementation of the 'SourceNumberType' enum.

    TODO: type enum description here.

    Attributes:
        INTERNATIONAL: TODO: type description here.
        ALPHANUMERIC: TODO: type description here.
        SHORTCODE: TODO: type description here.

    """

    INTERNATIONAL = 'INTERNATIONAL'

    ALPHANUMERIC = 'ALPHANUMERIC'

    SHORTCODE = 'SHORTCODE'
