# -*- coding: utf-8 -*-

"""
messages

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import base64


class BasicAuth:

    def __init__(self, basic_auth_user_name, basic_auth_password):
        self._basic_auth_user_name = basic_auth_user_name
        self._basic_auth_password = basic_auth_password

    def validate_arguments(self):
        if self._basic_auth_user_name and self._basic_auth_password:
            return True

    def apply(self, http_request):
        """ Add basic authentication to the request.

        Args:
            http_request (HttpRequest): The HttpRequest object to which
                authentication will be added.

        """
        username = self._basic_auth_user_name
        password = self._basic_auth_password
        joined = "{}:{}".format(username, password)
        encoded = base64.b64encode(str.encode(joined)).decode('iso-8859-1')
        header_value = "Basic {}".format(encoded)
        http_request.headers["Authorization"] = header_value

    def error_message(self):
        """Display error message on occurrence of authentication faliure
        in BasicAuth

        """
        return "BasicAuth: _basic_auth_user_name or _basic_auth_password is undefined."